#生产环境
server:
  servlet:
    path: /api/v1
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.207.93.53:3306/wo_life?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: gy123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true